version: '3.7'

services:
  app:
    container_name: django_library_api
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py qcluster &
             python notification/telegram_server.py &
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    container_name: postgres_service
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - service_data:/var/lib/postgresql/data/

  redis-server:
    image: redis
    container_name: redis-server
    ports:
      - "6379:6379"

volumes:
    service_data:
        driver: local
