# Generated by Django 4.2.4 on 2023-08-15 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('borrowing', '0002_alter_borrowing_actual_return_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], max_length=7)),
                ('type', models.CharField(choices=[('PAYMENT', 'Payment'), ('FINE', 'Fine')], max_length=7)),
                ('session_url', models.URLField(null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('money_to_pay', models.DecimalField(decimal_places=2, max_digits=8)),
                ('borrowing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='borrowing.borrowing')),
            ],
        ),
    ]
