# Generated by Django 4.2.4 on 2023-08-16 18:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0002_alter_borrowing_actual_return_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ["-is_active", "expected_return_date"]},
        ),
    ]
