# Generated by Django 4.2.4 on 2023-08-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="chat_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(default="n1pgZxc15Q4", max_length=8),
        ),
    ]
