# Generated by Django 4.2.4 on 2023-08-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_user_chat_id_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
